---
- name: daemon-reload
  become: true
  systemd:
    daemon_reload: true

- name: restart node-exporter
  become: true
  systemd:
    name: prometheus-node-exporter.service
    state: restarted
    daemon_reload: true
