---
- name: Create docker config directory
  become: true
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Configure docker
  become: true
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0600"

- name: Add Docker GPG apt key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  become: true
  apt:
    name: docker-ce
    update_cache: true
    state: present

- name: Remove old docker-compose
  become: true
  apt:
    name: docker-compose
    state: absent

- name: Install Docker Module for Python
  become: true
  pip:
    name:
      - docker==5.0.3
      - docker-compose==1.29.2
    state: present

- name: Install Loki plugin
  become: true
  community.docker.docker_plugin:
    plugin_name: grafana/loki-docker-driver:latest
    state: present
    alias: loki
  when: docker_loki_plugin_required

- name: Enable Loki plugin
  become: true
  community.docker.docker_plugin:
    plugin_name: grafana/loki-docker-driver:latest
    state: enable
    alias: loki
  when: docker_loki_plugin_required
